version: 2
jobs:
  build:
    environment:
      - APP_NAME: ci-base
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - run: docker login -u ${DOCKER_HUB_USER} -p ${DOCKER_HUB_PASS}
      - run: docker build -t pure/${APP_NAME}:latest .
      - run: docker push pure/${APP_NAME}:latest

workflows:
  version: 2
  deploy:
    jobs:
      - build:
          context: pure-global
          filters:
            branches:
              only:
                - master
